#!/bin/bash
# =====================================================
# LXC-Erstellung: OMV-ready Container auf Proxmox 9
# Debian 12, Privileged, Nesting, statische IP
# Host-HDD ZFS als Bind-Mount
# Root automatisch gesetzt
# OMV-Admin-Passwort vergeben
# =====================================================
set -e

# ------------------------
# Variablen anpassen
# ------------------------
HOSTNAME=omv
TEMPLATE="/bpool/template/cache/debian-12-standard_12.12-1_amd64.tar.zst"
#TEMPLATE="/var/lib/vz/template/cache/debian-13-standard_13.1-1_amd64.tar.zst"
STORAGE="local-zfs"          # dir-Storage
DISK_SIZE="16"
MEMORY=4096 #8192 #16384 #24576
CORES=2
ZPOOL_PATH="/mnt/hdd"           # optional Host-HDD
ZPOOL_MOUNT="/mnt/hdd" 		# Mountpoint im Container
GATEWAY="192.168.178.1"
NETMASK="24"
ROOT_PASS="11111"        # Root-Passwort im Container


# ------------------------
# Nächste freie CTID ermitteln (150-200)
# ------------------------
for i in $(seq 150 200); do
  if ! pvesh get /cluster/resources --type vm | grep -qE "(qemu|lxc)/$i"; then
    CTID=$i
    break
  fi
done

if [ -z "$CTID" ]; then
  echo "Fehler: Keine freie CTID zwischen 101 und 998 gefunden!"
  exit 1
fi

IP="192.168.178.$CTID"
echo "==> Nächste freie CTID: $CTID"
echo "==> Statische IP: $IP"


# ------------------------
# LXC erstellen
# ------------------------
pct create $CTID $TEMPLATE \
  --hostname $HOSTNAME \
  --cores $CORES \
  --memory $MEMORY \
  --swap 0 \
  --rootfs $STORAGE:$DISK_SIZE \
  --net0 name=eth0,bridge=vmbr0,ip=$IP/$NETMASK,gw=$GATEWAY,type=veth \
  --unprivileged 0 \
  --features nesting=1,fuse=1,keyctl=1
  #--apparmor=unconfined

# ZFS-Pool als Mount einhängen
pct set $CTID -mp0 $ZPOOL_PATH,mp=$ZPOOL_MOUNT,backup=0

# ------------------------
# Container starten
# ------------------------
pct start $CTID

# ------------------------
# Root-Passwort setzen
# ------------------------
pct exec $CTID -- bash -c "echo 'root:$ROOT_PASS' | chpasswd"

# ------------------------
# Grundsystem vorbereiten
# ------------------------
pct exec $CTID -- bash -c "apt update -y && apt upgrade -y"
pct exec $CTID -- apt install -y wget curl gnupg lsb-release sudo

# ------------------------
# OMV installieren
# ------------------------
pct exec $CTID -- bash -c "wget -O - https://github.com/OpenMediaVault-Plugin-Developers/installScript/raw/master/install | bash"


# ------------------------
# Fertig
# ------------------------
echo "-----------------------------------------------------"
echo "Container $CTID erstellt und gestartet mit IP: $IP"
echo "Root-Passwort im Container: $ROOT_PASS"
echo "OMV-Admin-Passwort: openmediavault"
echo "Zugriff auf Container: pct enter $CTID"
echo "OMV-WebGUI: http://$IP/"
echo "-----------------------------------------------------"
echo "Starte omv-firstaid für Admin-Passwort und weitere Einstellungen..."
pct exec $CTID -- omv-firstaid
